package codes.swistak.batterymonitor

internal object SettingsKeys {
    const val KEY_ENABLE_LOGGING: String = "enable_logging"
    const val KEY_MAX_LOG_AGE: String = "max_log_age"
    const val KEY_ICON_CONTENT: String = "icon_content"
    const val KEY_SHOW_ICON_UNIT: String = "show_icon_unit"
    const val KEY_CONVERT_F: String = "convert_to_fahrenheit"
    const val KEY_NOTIFY_STATUS_DURATION: String = "notify_status_duration"
    const val KEY_AUTOSTART: String = "autostart"
    const val KEY_PREDICTION_TYPE: String = "prediction_type"
    const val KEY_STATUS_DUR_EST: String = "status_dur_est"
    const val KEY_INDICATE_CHARGING: String = "indicate_charging"
    const val KEY_CHIP_CONTENT: String = "chip_content"
    const val KEY_CHIP_SWITCHING_INTERVAL: String = "chip_switching_interval"
    const val KEY_CHIP_INDICATE_CHARGING: String = "chip_indicate_charging"
    const val KEY_LIVE_UPDATE_DISPLAY: String = "live_update_display"
    const val KEY_LIVE_UPDATE_KEEP_MAIN_NOTIFICATION: String = "live_update_keep_main_notification"
    const val KEY_RED: String = "use_red"
    const val KEY_RED_THRESH: String = "red_threshold"
    const val KEY_AMBER: String = "use_amber"
    const val KEY_AMBER_THRESH: String = "amber_threshold"
    const val KEY_GREEN: String = "use_green"
    const val KEY_GREEN_THRESH: String = "green_threshold"
    const val KEY_TOP_LINE: String = "top_line"
    const val KEY_BOTTOM_LINE: String = "bottom_line"
    const val KEY_TIME_REMAINING_VERBOSITY: String = "time_remaining_verbosity"
    const val KEY_STATUS_DURATION_IN_VITAL_SIGNS: String = "status_duration_in_vital_signs"
    const val KEY_ENABLE_CURRENT_HACK: String = "enable_current_hack"
    const val KEY_CURRENT_HACK_PREFER_FS: String = "current_hack_prefer_fs"
    const val KEY_CURRENT_HACK_MULTIPLIER: String = "current_hack_multiplier"
    const val KEY_DISPLAY_CURRENT_IN_VITAL_STATS: String = "display_current_in_vital_stats"
    const val KEY_PREFER_CURRENT_AVG_IN_VITAL_STATS: String = "prefer_current_avg_in_vital_stats"
    const val KEY_DISPLAY_CURRENT_IN_MAIN_WINDOW: String = "display_current_in_main_window"
    const val KEY_PREFER_CURRENT_AVG_IN_MAIN_WINDOW: String = "prefer_current_avg_in_main_window"
    const val KEY_AUTO_REFRESH_CURRENT_IN_MAIN_WINDOW: String =
        "auto_refresh_current_in_main_window"
    const val KEY_UI_COLOR: String = "ui_color"
    const val KEY_ENABLE_ADVANCED_STATS: String = "enable_advanced_stats"
}
